"""Copy operations exposed on the TileLang language surface."""

from __future__ import annotations
from typing import Literal, Any
from tilelang._typing import BufferLikeType
from tilelang.utils.language import (
    to_buffer_region,
    legalize_pairwise_extents,
)
from tilelang.language.utils import get_extent
import tvm
from tvm import ir, tir


def _normalize_copy_regions(
    src: BufferLikeType, dst: BufferLikeType
) -> tuple[
    tir.BufferRegion | tir.BufferLoad | tir.Buffer,
    tir.BufferRegion | tir.BufferLoad | tir.Buffer,
]:
    # If both side are buffers, we should make sure their shapes are equal
    if isinstance(src, tir.Buffer) and isinstance(dst, tir.Buffer):
        ir.assert_structural_equal(src.shape, dst.shape)

    src_extent = get_extent(src)
    dst_extent = get_extent(dst)

    src_is_scalar_load = src_extent is None and isinstance(src, tir.BufferLoad)
    dst_is_scalar_load = dst_extent is None and isinstance(dst, tir.BufferLoad)

    # copy(buffer_a[i], buffer_b[i]) where both are BufferLoad nodes
    # In this case, lower it to a simple BufferStore: buffer_b[i] = buffer_a[i]
    if src_is_scalar_load and dst_is_scalar_load:
        return src, dst

    assert src_extent or dst_extent, "Can't deduce copy extents from args. Both src and dst miss extents info."
    # Treat missing extent as length-matched ones for convenience. This provides limited
    # broadcasting-like syntactic sugar, but does not implement general broadcasting support.
    src_extent = list(src_extent) if src_extent else [1] * len(dst_extent)
    dst_extent = list(dst_extent) if dst_extent else [1] * len(src_extent)

    # Align and broadcast extents from the right (tail) side.
    # This is majorly for supporting some syntactic sugar, not the whole broadcasting ability of copy op.
    src_extent, dst_extent = legalize_pairwise_extents(src_extent, dst_extent)

    # Use legalized extents for src and dst respectively.
    src = to_buffer_region(src, access_type="r", extents=src_extent)
    dst = to_buffer_region(dst, access_type="w", extents=dst_extent)
    return src, dst


def copy(
    src: BufferLikeType,
    dst: BufferLikeType,
    *,
    coalesced_width: int | None = None,
    disable_tma: bool = False,
    eviction_policy: Literal["evict_normal", "evict_first", "evict_last"] | None = None,
    annotations: dict | None = None,
    loop_layout: Any | None = None,
) -> tir.PrimExpr | tir.Stmt:
    """Copy data between memory regions.

    Args:
        src (Union[tir.Buffer, tir.BufferLoad, tir.BufferRegion]): Source memory region
        dst (Union[tir.Buffer, tir.BufferLoad, tir.BufferRegion]): Destination memory region
        coalesced_width (Optional[int], keyword-only): Width for coalesced memory access. Defaults to None.
        disable_tma (bool, keyword-only): Whether to disable TMA acceleration. Defaults to False.
        eviction_policy (Optional[str], keyword-only): Cache eviction policy. Defaults to None.
        annotations (Optional[dict], keyword-only): Additional annotations dict. If provided,
            coalesced_width, disable_tma, and eviction_policy can also be specified here.
            Values in annotations take precedence over individual arguments.
        loop_layout (Optional[Fragment], keyword-only): A parallel loop layout hint for the SIMT copy
            (only valid for normal SIMT copy; incompatible with TMA/LDSM/STSM/TMem). When provided,
            it is attached to the outermost parallel loop generated by this copy.

    Raises:
        TypeError: If copy extents cannot be deduced from arguments

    Returns:
        tir.Call: A handle to the copy operation

    Range handling notes:
    - Accepts `Buffer`/`BufferRegion`/`BufferLoad` on either side. Extents are
      derived as follows: `Buffer -> shape`, `BufferRegion -> [r.extent]`,
      `BufferLoad -> extents from its inferred/encoded region`.
    - Normally, we require the extents of both sides to be the same. If they
      differ, the copy instruction follows an internal rule to select one side
      as the base range and create iteration space. This may generate unexpected
      code. And if some dimensions are 1, unexpected errors may happen.
    - Small Optimization: If both `src` and `dst` are scalar `BufferLoad` without
      region extents, lowers to a direct store: `dst[...] = src[...]`.
    - Syntactic Sugar: TileLang supports passing the head address of a buffer to represent
      the whole buffer if there are no ambiguity. For example, T.copy(A, A_shared[i, j]).
      To support this, we need some special shape checking. But remember currently we don't
      support something like "broadcast".
    - The finalized extents are encoded with `tl.region` via `to_buffer_region`
      and passed through to the backend; low-level loop construction and any
      scope-specific decisions happen during lowering.
    """
    src, dst = _normalize_copy_regions(src, dst)
    if isinstance(src, tir.BufferLoad) and isinstance(dst, tir.BufferLoad):
        return tir.BufferStore(dst.buffer, src, dst.indices)

    # Build annotations dict
    ann = annotations.copy() if annotations else {}

    # Individual arguments take lower precedence than annotations
    if "coalesced_width" not in ann and coalesced_width is not None:
        ann["coalesced_width"] = coalesced_width
    if "disable_tma" not in ann and disable_tma:
        ann["disable_tma"] = disable_tma
    if "eviction_policy" not in ann and eviction_policy is not None:
        eviction_policy_map = {"evict_normal": 0, "evict_first": 1, "evict_last": 2}
        ann["eviction_policy"] = eviction_policy_map[eviction_policy]

    # Parallel loop layout hint (Fragment). Mirrors T.Parallel(loop_layout=...)
    if loop_layout is not None and "parallel_loop_layout" not in ann:
        ann["parallel_loop_layout"] = loop_layout

    return tir.call_intrin("handle", tir.op.Op.get("tl.tileop.copy"), src, dst, annotations=ann if ann else None)


def async_copy(
    src: BufferLikeType,
    dst: BufferLikeType,
    *,
    coalesced_width: int | None = None,
    annotations: dict | None = None,
    loop_layout: Any | None = None,
) -> tir.PrimExpr | tir.Stmt:
    """Asynchronous copy primitive lowered through cp.async.

    This operator is intended for explicitly asynchronous global->shared copy.
    The backend enforces cp.async constraints and emits:
      `ptx_cp_async(...)` + `ptx_commit_group()`.
    No wait is auto-inserted for `T.async_copy`; synchronization is explicit.

    Args:
        src (Union[tir.Buffer, tir.BufferLoad, tir.BufferRegion]): Source memory region
        dst (Union[tir.Buffer, tir.BufferLoad, tir.BufferRegion]): Destination memory region
        coalesced_width (Optional[int], keyword-only): Width for coalesced memory access. Defaults to None.
        annotations (Optional[dict], keyword-only): Additional annotations dict.
        loop_layout (Optional[Fragment], keyword-only): A parallel loop layout hint for the SIMT copy loop.

    Returns:
        tir.Call: A handle to the async copy operation
    """
    src, dst = _normalize_copy_regions(src, dst)
    if isinstance(src, tir.BufferLoad) and isinstance(dst, tir.BufferLoad):
        return tir.BufferStore(dst.buffer, src, dst.indices)

    ann = annotations.copy() if annotations else {}
    if "coalesced_width" not in ann and coalesced_width is not None:
        ann["coalesced_width"] = coalesced_width
    if loop_layout is not None and "parallel_loop_layout" not in ann:
        ann["parallel_loop_layout"] = loop_layout

    return tir.call_intrin(
        "handle",
        tir.op.Op.get("tl.tileop.async_copy"),
        src,
        dst,
        annotations=ann if ann else None,
    )


def tma_copy(
    src: BufferLikeType,
    dst: BufferLikeType,
    *,
    barrier=None,
    eviction_policy: Literal["evict_normal", "evict_first", "evict_last"] | None = None,
    annotations: dict | None = None,
) -> tir.PrimExpr | tir.Stmt:
    """TMA copy with user-managed synchronization.

    For **loads** (global -> shared): issues expect_tx + tma_load (no wait).
    Unlike T.copy() which emits a full synchronous TMA sequence (arrive + load + wait),
    T.tma_copy() emits only the producer part (expect_tx + tma_load).
    The user manages synchronization explicitly via T.barrier_arrive() and
    T.mbarrier_wait_parity(). ``barrier`` is required for loads.

    For **stores** (shared -> global): issues tma_store + tma_store_arrive (no wait).
    Unlike T.copy() which emits tma_store + tma_store_arrive + tma_store_wait,
    T.tma_copy() omits the wait so the user can batch multiple stores before
    calling T.tma_store_wait() explicitly. ``barrier`` is not needed for stores.

    Args:
        src: Source memory region (global or shared)
        dst: Destination memory region (shared or global)
        barrier: Mbarrier (from T.alloc_barrier()) for TMA load synchronization.
            Required for loads (global -> shared). Not needed for stores.
            The TMA load will arrive at this barrier with expected byte count.
            The user must wait on the same barrier via T.mbarrier_wait_parity().
        eviction_policy: Cache eviction policy. Defaults to None.
        annotations: Additional annotations dict. Values in annotations take
            precedence over individual arguments.

    Returns:
        tir.Call: A handle to the tma_copy operation
    """
    # If both side are buffers, we should make sure their shapes are equal
    if isinstance(src, tir.Buffer) and isinstance(dst, tir.Buffer):
        ir.assert_structural_equal(src.shape, dst.shape)

    src_extent = get_extent(src)
    dst_extent = get_extent(dst)

    assert src_extent or dst_extent, "Can't deduce copy extents from args. Both src and dst miss extents info."
    src_extent = list(src_extent) if src_extent else [1] * len(dst_extent)
    dst_extent = list(dst_extent) if dst_extent else [1] * len(src_extent)

    src_extent, dst_extent = legalize_pairwise_extents(src_extent, dst_extent)

    src = to_buffer_region(src, access_type="r", extents=src_extent)
    dst = to_buffer_region(dst, access_type="w", extents=dst_extent)

    ann = annotations.copy() if annotations else {}

    if barrier is not None:
        from .builtin import _mbar_to_buffer_load

        ann["barrier"] = _mbar_to_buffer_load(barrier)

    if "eviction_policy" not in ann and eviction_policy is not None:
        eviction_policy_map = {"evict_normal": 0, "evict_first": 1, "evict_last": 2}
        ann["eviction_policy"] = eviction_policy_map[eviction_policy]

    return tir.call_intrin("handle", tir.op.Op.get("tl.tileop.tma_copy"), src, dst, annotations=ann if ann else None)


# Mirrors src/op/utils.cc::to_CUtensorMapDataType so descriptor args round-trip
# through the host-side tvm_tensormap_create_tiled call.
_CU_TENSOR_MAP_DATA_TYPE = {
    "uint8": 0,
    "uint16": 1,
    "uint32": 2,
    "int32": 3,
    "uint64": 4,
    "int64": 5,
    "float16": 6,
    "float32": 7,
    "float64": 8,
    "bfloat16": 9,
}
_CU_TENSOR_MAP_INTERLEAVE_NONE = 0
_CU_TENSOR_MAP_SWIZZLE_NONE = 0
_CU_TENSOR_MAP_SWIZZLE_32B = 1
_CU_TENSOR_MAP_SWIZZLE_64B = 2
_CU_TENSOR_MAP_SWIZZLE_128B = 3
_CU_TENSOR_MAP_L2_PROMOTION_L2_128B = 2
_CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE = 0


def _swizzle_str_to_int(s):
    if s in (None, "none", 0):
        return _CU_TENSOR_MAP_SWIZZLE_NONE
    if s in ("32B", 32, "32"):
        return _CU_TENSOR_MAP_SWIZZLE_32B
    if s in ("64B", 64, "64"):
        return _CU_TENSOR_MAP_SWIZZLE_64B
    if s in ("128B", 128, "128"):
        return _CU_TENSOR_MAP_SWIZZLE_128B
    raise ValueError(f"Unknown swizzle mode: {s!r}")


def tma_gather4(
    src: tir.Buffer,
    dst: tir.Buffer,
    col: tir.PrimExpr,
    rows,
    *,
    barrier,
    swizzle=None,
    eviction_policy: Literal["evict_normal", "evict_first", "evict_last"] | None = None,
):
    """Issue a TMA tile::gather4 load (sm_90+).

    Loads four arbitrary rows of a 2D global tensor ``src`` into a 2D shared
    tile ``dst`` of shape ``(4, K_box)``.

    The caller is responsible for issuing ``T.mbarrier_expect_tx`` (use
    :func:`tma_gather4_bytes`) before this call, and for ``barrier_arrive`` /
    ``mbarrier_wait_parity`` after. The call must also be inside a
    leader-thread guard such as ``if T.shuffle_elect(num_threads):``.

    Args:
        src: Global memory buffer (rank-2). Innermost stride must be 1.
        dst: Shared memory buffer of shape ``(4, K_box)``.
        col: Scalar i32 column origin.
        rows: Sequence of 4 i32 row indices.
        barrier: Mbarrier handle.
        swizzle: One of None / "32B" / "64B" / "128B" (or int 0/32/64/128).
        eviction_policy: Cache eviction policy.
    """
    if not isinstance(src, tir.Buffer):
        raise TypeError("tma_gather4 src must be a tir.Buffer (global)")
    if not isinstance(dst, tir.Buffer):
        raise TypeError("tma_gather4 dst must be a tir.Buffer (shared)")
    if len(src.shape) != 2:
        raise ValueError(f"tma_gather4 expects rank-2 global buffer, got {len(src.shape)}")
    if len(dst.shape) != 2:
        raise ValueError(f"tma_gather4 expects rank-2 shared buffer (4 x K_box), got {len(dst.shape)}")
    rows = list(rows)
    if len(rows) != 4:
        raise ValueError(f"tma_gather4 expects exactly 4 row indices, got {len(rows)}")

    from .builtin import (
        create_tma_descriptor,
        tma_load_gather4 as _tma_load_gather4,
        _mbar_to_buffer_load,
    )

    dtype_name = src.dtype
    if dtype_name not in _CU_TENSOR_MAP_DATA_TYPE:
        raise ValueError(f"Unsupported dtype for TMA gather4: {dtype_name}")
    dtype_int = _CU_TENSOR_MAP_DATA_TYPE[dtype_name]

    g_shape_rev = [src.shape[1], src.shape[0]]
    elem_bits = tvm.DataType(dtype_name).bits
    elem_bytes = elem_bits // 8
    if not src.strides:
        g_stride_rev = [1, src.shape[1]]
    else:
        g_stride_rev = [src.strides[1], src.strides[0]]
    g_stride_bytes = [g_stride_rev[0] * elem_bytes, g_stride_rev[1] * elem_bytes]

    K_box = dst.shape[1]
    box_rev = [K_box, 1]
    smem_stride = [1, 1]

    rank = 2
    swizzle_int = _swizzle_str_to_int(swizzle)

    desc_args = [
        dtype_int,
        rank,
        src.data,
        *g_shape_rev,
        *g_stride_bytes,
        *box_rev,
        *smem_stride,
        _CU_TENSOR_MAP_INTERLEAVE_NONE,
        swizzle_int,
        _CU_TENSOR_MAP_L2_PROMOTION_L2_128B,
        _CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE,
    ]
    desc = create_tma_descriptor(*desc_args)

    smem_addr = dst.access_ptr("w")
    bar_load = _mbar_to_buffer_load(barrier)

    eviction_policy_map = {"evict_normal": 0, "evict_first": 1, "evict_last": 2}
    ep = 0 if eviction_policy is None else eviction_policy_map[eviction_policy]

    return _tma_load_gather4(
        desc, bar_load, smem_addr, col, rows[0], rows[1], rows[2], rows[3], ep
    )


def tma_gather4_bytes(K_box, dtype: str) -> int:
    """Transaction byte count for a 4-row gather4 of width ``K_box``. Pass
    to ``T.mbarrier_expect_tx`` immediately before ``T.tma_gather4``.
    """
    if dtype not in _CU_TENSOR_MAP_DATA_TYPE:
        raise ValueError(f"Unsupported dtype: {dtype}")
    elem_bytes = tvm.DataType(dtype).bits // 8
    return 4 * K_box * elem_bytes


def tma_scatter4(
    src: tir.Buffer,
    dst: tir.Buffer,
    col: tir.PrimExpr,
    rows,
    *,
    swizzle=None,
    eviction_policy: Literal["evict_normal", "evict_first", "evict_last"] | None = None,
):
    """Issue a TMA tile::scatter4 store (sm_90+).

    Stores a 2D shared tile of shape ``(4, K_box)`` to four arbitrary rows
    of a 2D global tensor ``dst``.

    The caller is responsible for ``tma_store_arrive`` / ``tma_store_wait``,
    and the call must be inside a leader-thread guard.
    """
    if not isinstance(src, tir.Buffer):
        raise TypeError("tma_scatter4 src must be a tir.Buffer (shared)")
    if not isinstance(dst, tir.Buffer):
        raise TypeError("tma_scatter4 dst must be a tir.Buffer (global)")
    if len(src.shape) != 2:
        raise ValueError(f"tma_scatter4 expects rank-2 shared buffer (4 x K_box), got {len(src.shape)}")
    if len(dst.shape) != 2:
        raise ValueError(f"tma_scatter4 expects rank-2 global buffer, got {len(dst.shape)}")
    rows = list(rows)
    if len(rows) != 4:
        raise ValueError(f"tma_scatter4 expects exactly 4 row indices, got {len(rows)}")

    from .builtin import (
        create_tma_descriptor,
        tma_store_scatter4 as _tma_store_scatter4,
    )

    dtype_name = dst.dtype
    if dtype_name not in _CU_TENSOR_MAP_DATA_TYPE:
        raise ValueError(f"Unsupported dtype for TMA scatter4: {dtype_name}")
    dtype_int = _CU_TENSOR_MAP_DATA_TYPE[dtype_name]

    g_shape_rev = [dst.shape[1], dst.shape[0]]
    elem_bits = tvm.DataType(dtype_name).bits
    elem_bytes = elem_bits // 8
    if not dst.strides:
        g_stride_rev = [1, dst.shape[1]]
    else:
        g_stride_rev = [dst.strides[1], dst.strides[0]]
    g_stride_bytes = [g_stride_rev[0] * elem_bytes, g_stride_rev[1] * elem_bytes]

    K_box = src.shape[1]
    box_rev = [K_box, 1]
    smem_stride = [1, 1]

    rank = 2
    swizzle_int = _swizzle_str_to_int(swizzle)

    desc_args = [
        dtype_int,
        rank,
        dst.data,
        *g_shape_rev,
        *g_stride_bytes,
        *box_rev,
        *smem_stride,
        _CU_TENSOR_MAP_INTERLEAVE_NONE,
        swizzle_int,
        _CU_TENSOR_MAP_L2_PROMOTION_L2_128B,
        _CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE,
    ]
    desc = create_tma_descriptor(*desc_args)

    smem_addr = src.access_ptr("r")

    eviction_policy_map = {"evict_normal": 0, "evict_first": 1, "evict_last": 2}
    ep = 0 if eviction_policy is None else eviction_policy_map[eviction_policy]

    return _tma_store_scatter4(
        desc, smem_addr, col, rows[0], rows[1], rows[2], rows[3], ep
    )


def transpose(
    src: BufferLikeType,
    dst: BufferLikeType,
) -> tir.PrimExpr:
    """Transpose a 2D buffer in shared memory: dst[j, i] = src[i, j].

    Both src and dst should be shared memory buffers.
    If src has shape (M, N), dst should have shape (N, M).

    Args:
        src: Source buffer or region of shape (..., M, N).
        dst: Destination buffer or region of shape (..., N, M).

    Returns:
        tir.Call: A handle to the transpose operation.
    """
    src_extent = get_extent(src)
    dst_extent = get_extent(dst)

    assert src_extent is not None, "Cannot deduce extent for transpose src."
    assert dst_extent is not None, "Cannot deduce extent for transpose dst."
    assert len(src_extent) >= 2, "Transpose requires at least 2D buffers."
    assert len(dst_extent) >= 2, "Transpose requires at least 2D buffers."

    src = to_buffer_region(src, access_type="r")
    dst = to_buffer_region(dst, access_type="w")

    return tir.call_intrin(
        "handle",
        tir.op.Op.get("tl.tileop.transpose"),
        src,
        dst,
    )


def c2d_im2col(
    img: BufferLikeType,
    col: BufferLikeType,
    nhw_step: tir.PrimExpr,
    c_step: tir.PrimExpr,
    kernel: int,
    stride: int,
    dilation: int,
    pad: int,
    eviction_policy: Literal["evict_normal", "evict_first", "evict_last"] | None = None,
) -> tir.PrimExpr:
    """Perform im2col transformation for 2D convolution.

    Args:
        img (tir.Buffer): Input image buffer
        col (tir.Buffer): Output column buffer
        nhw_step (tir.PrimExpr): Step size for batch and spatial dimensions
        c_step (tir.PrimExpr): Step size for channel dimension
        kernel (int): Kernel size
        stride (int): Stride of the convolution
        dilation (int): Dilation rate
        pad (int): Padding size

    Returns:
        tir.Call: A handle to the im2col operation
    """
    if eviction_policy is None:
        eviction_policy = 0
    else:
        eviction_policy = {"evict_normal": 0, "evict_first": 1, "evict_last": 2}[eviction_policy]
    img_region = to_buffer_region(img, access_type="r")
    col_region = to_buffer_region(col, access_type="w")
    return tir.call_intrin(
        "handle",
        tir.op.Op.get("tl.tileop.c2d_im2col"),
        img_region,
        col_region,
        nhw_step,
        c_step,
        kernel,
        stride,
        dilation,
        pad,
        eviction_policy,
    )
