include_guard(GLOBAL)

# Prefer the build interpreter, then active/project environments and PATH.
function(tilelang_get_python_candidates OUTPUT_VAR)
  set(_candidates "${Python_EXECUTABLE}" "${Python3_EXECUTABLE}" "${PYTHON_EXECUTABLE}")
  if(WIN32)
    set(_suffix "Scripts/python.exe")
  else()
    set(_suffix "bin/python")
  endif()
  foreach(_root IN ITEMS "$ENV{VIRTUAL_ENV}" "$ENV{UV_PROJECT_ENVIRONMENT}"
                         "${CMAKE_SOURCE_DIR}/.venv" "${CMAKE_SOURCE_DIR}/venv")
    if(_root)
      list(APPEND _candidates "${_root}/${_suffix}")
    endif()
  endforeach()
  find_program(_tilelang_python_on_path NAMES python3 python)
  list(APPEND _candidates "${_tilelang_python_on_path}")
  set(_existing "")
  foreach(_candidate IN LISTS _candidates)
    if(EXISTS "${_candidate}")
      list(APPEND _existing "${_candidate}")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES _existing)
  set(${OUTPUT_VAR} "${_existing}" PARENT_SCOPE)
endfunction()

function(tilelang_get_python_interpreter OUTPUT_VAR)
  foreach(_var IN ITEMS Python_EXECUTABLE Python3_EXECUTABLE PYTHON_EXECUTABLE)
    if(DEFINED ${_var} AND EXISTS "${${_var}}")
      set(${OUTPUT_VAR} "${${_var}}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  set(${OUTPUT_VAR} "${Python3_EXECUTABLE}" PARENT_SCOPE)
endfunction()

function(tilelang_probe_python_sdk SCRIPT OUTPUT_VAR PYTHON_VAR)
  tilelang_get_python_candidates(_candidates)
  foreach(_python IN LISTS _candidates)
    execute_process(COMMAND "${_python}" "${SCRIPT}" ${ARGN}
      OUTPUT_VARIABLE _output OUTPUT_STRIP_TRAILING_WHITESPACE
      RESULT_VARIABLE _result)
    if(_result EQUAL 0 AND NOT _output STREQUAL "")
      set(${OUTPUT_VAR} "${_output}" PARENT_SCOPE)
      set(${PYTHON_VAR} "${_python}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${OUTPUT_VAR} "" PARENT_SCOPE)
  set(${PYTHON_VAR} "" PARENT_SCOPE)
endfunction()
