name: Dist
on: [pull_request]

env:
  PYTHON_VERSION: '3.12'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-wheels:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-14]
        include:
        - os: ubuntu-22.04
          CUDA_VERSION: 12.1
        - os: ubuntu-22.04-arm
          CUDA_VERSION: 12.8
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      CUDA_VERSION: ${{ matrix.CUDA_VERSION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2
        env:
          CIBW_BUILD: cp312-*
          CIBW_ARCHS: auto64
          CIBW_ARCHS_MACOS: auto64 niversal2
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ env.PYTHON_VERSION }}-${{ runner.os }}-${{ runner.arch }}
          path: wheelhouse/*.whl
          if-no-files-found: error
