name: Dist
on: [pull_request]

env:
  PYTHON_VERSION: '3.12'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-wheels:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-14]
      include:
      - os: ubuntu-22.04
        CUDA_VERSION: 12.1
      - os: ubuntu-22.04-arm
        CUDA_VERSION: 12.8
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      CUDA_VERSION: ${{ matrix.CUDA_VERSION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==3.2.0

    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
        echo "whl_name=$(ls wheelhouse | head -n1)" >> $GITHUB_OUTPUT

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.repair.outputs.whl_name }}.zip
        path: wheelhouse/${{ steps.repair.outputs.whl_name }}
        compression-level: 0
